services:
  mysql-master:
    image: mysql:8.0.36
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/master:/var/lib/mysql
      - ./init/master:/docker-entrypoint-initdb.d

  mysql-slave:
    image: mysql:8.0.36
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/slave:/var/lib/mysql
      - ./init/slave:/docker-entrypoint-initdb.d

  phpmyadmin-master:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-master
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306

  phpmyadmin-slave:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-slave
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql-slave
      PMA_PORT: 3306

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    restart: always
    ports:
      - "6032:6032"
      - "6033:6033"
    depends_on:
      - mysql-master
      - mysql-slave
    volumes:
      - ./init/proxysql/init.sql:/init.sql
    command: >
      /bin/bash -c '
        /usr/bin/proxysql --initial &

        for i in {1..10}; do
          echo "⌛ Waiting for ProxySQL to be ready ($i)..."
          sleep 3
          mysql -u admin -padmin -h 127.0.0.1 -P6032 -e "SELECT 1" && break
        done

        echo "🚀 Running init.sql"
        mysql -u admin -padmin -h 127.0.0.1 -P6032 < /init.sql || true

        tail -f /dev/null
      '

volumes:
  master-data:
  slave-data:
  proxysql-data:
