networks:
  cakephp-network:
    external: true

services:
  mysql-master:
    image: mysql:lts
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REPL_USER: ${REPL_USER}
      REPL_PASSWORD: ${REPL_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - master-data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./init/master:/docker-entrypoint-initdb.d:ro
    networks:
      - cakephp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  mysql-slave1:
    image: mysql:lts
    container_name: mysql-slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REPL_USER: ${REPL_USER}
      REPL_PASSWORD: ${REPL_PASSWORD}
    depends_on:
      - mysql-master
    volumes:
      - slave1-data:/var/lib/mysql
      - ./slave1/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./init/slave/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh:ro
    networks:
      - cakephp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  mysql-slave2:
    image: mysql:lts
    container_name: mysql-slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REPL_USER: ${REPL_USER}
      REPL_PASSWORD: ${REPL_PASSWORD}
    depends_on:
      - mysql-master
    volumes:
      - slave2-data:/var/lib/mysql
      - ./slave2/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./init/slave/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh:ro
    networks:
      - cakephp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    restart: always
    environment:
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    ports:
      - "6032:6032"  # admin
      - "6033:6033"  # client
    volumes:
      - proxysql-data:/var/lib/proxysql
      - ./init/proxysql:/init/proxysql
    command: ["/bin/bash", "/init/proxysql/entrypoint.sh"]
    env_file:
      - .env
    networks:
      - cakephp-network

  phpmyadmin-master:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-master
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306
    networks:
      - cakephp-network

volumes:
  master-data:
  slave1-data:
  slave2-data:
  proxysql-data:
